"""phase8_print_job_history

Revision ID: 1a1eeb693473
Revises: b2111cbd78ca
Create Date: 2026-08-31 09:54:24.677324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1eeb693473'
down_revision: Union[str, Sequence[str], None] = 'b2111cbd78ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_job_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'SENT_TO_SHOP', 'ACCEPTED', 'PRINTING', 'COMPLETED', 'CANCELLED', name='printjobstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('CREATED', 'SENT_TO_SHOP', 'ACCEPTED', 'PRINTING', 'COMPLETED', 'CANCELLED', name='printjobstatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_job_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_job_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_status_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_status_history_print_job_id'), ['print_job_id'], unique=False)

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_page_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_column('selected_page_count')

    with op.batch_alter_table('print_job_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_job_status_history_print_job_id'))
        batch_op.drop_index(batch_op.f('ix_print_job_status_history_id'))
        batch_op.drop_index(batch_op.f('ix_print_job_status_history_changed_at'))

    op.drop_table('print_job_status_history')
    # ### end Alembic commands ###
