"""Add ShopPricing and PrintJob

Revision ID: 5462ce61485d
Revises: fb6d456d4676
Create Date: 2026-08-21 23:12:12.761153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5462ce61485d'
down_revision: Union[str, Sequence[str], None] = 'fb6d456d4676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('paper_size', sa.String(), nullable=False),
    sa.Column('color_mode', sa.String(), nullable=False),
    sa.Column('print_side', sa.String(), nullable=False),
    sa.Column('price_per_sheet', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'paper_size', 'color_mode', 'print_side', name='uix_shop_pricing')
    )
    with op.batch_alter_table('shop_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_pricing_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_pricing_shop_id'), ['shop_id'], unique=False)

    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('page_range', sa.String(), nullable=True),
    sa.Column('color_mode', sa.String(), nullable=False),
    sa.Column('paper_size', sa.String(), nullable=False),
    sa.Column('print_side', sa.String(), nullable=False),
    sa.Column('orientation', sa.String(), nullable=False),
    sa.Column('binding', sa.String(), nullable=True),
    sa.Column('stapling', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SENT_TO_SHOP', 'ACCEPTED', 'PRINTING', 'COMPLETED', 'CANCELLED', name='printjobstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('printing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_shop_id'), ['shop_id'], unique=False)

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_shop_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_customer_id'))

    op.drop_table('print_jobs')
    with op.batch_alter_table('shop_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_pricing_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_pricing_id'))

    op.drop_table('shop_pricing')
    # ### end Alembic commands ###
