"""Add shop qr and payment models

Revision ID: 8def19b65a9e
Revises: d1c19e18295d
Create Date: 2026-08-31 11:32:53.389344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8def19b65a9e'
down_revision: Union[str, Sequence[str], None] = 'd1c19e18295d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('qr_identifier', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='qrstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_qr_codes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_qr_codes_qr_identifier'), ['qr_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_shop_qr_codes_shop_id'), ['shop_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('method', sa.Enum('PAY_AT_SHOP', 'ONLINE', name='paymentmethod'), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_print_job_id'), ['print_job_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_print_job_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('shop_qr_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_qr_codes_shop_id'))
        batch_op.drop_index(batch_op.f('ix_shop_qr_codes_qr_identifier'))
        batch_op.drop_index(batch_op.f('ix_shop_qr_codes_id'))

    op.drop_table('shop_qr_codes')
    # ### end Alembic commands ###
