"""phase7_document_lifecycle

Revision ID: b2111cbd78ca
Revises: bb9521665b62
Create Date: 2026-08-31 09:27:08.352385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2111cbd78ca'
down_revision: Union[str, Sequence[str], None] = 'bb9521665b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('PENDING', 'UPLOADED', 'ACTIVE', 'IN_PRINT_JOB', 'PRINTED', 'EXPIRED', 'DELETED', 'FAILED', name='documentstatus'),
               existing_nullable=True)



    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'UPLOADED', 'ACTIVE', 'IN_PRINT_JOB', 'PRINTED', 'EXPIRED', 'DELETED', 'FAILED', name='documentstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###
