"""phase9b_secure_access_token

Revision ID: bb8ff055357d
Revises: 8def19b65a9e
Create Date: 2026-09-02 14:29:14.596958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8ff055357d'
down_revision: Union[str, Sequence[str], None] = '8def19b65a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='securetokenstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secure_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_print_job_id'), ['print_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_access_tokens_token_hash'), ['token_hash'], unique=True)



    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('secure_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_status'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_shop_id'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_print_job_id'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_secure_access_tokens_document_id'))

    op.drop_table('secure_access_tokens')
    # ### end Alembic commands ###
