"""phase6_shop_and_document_updates

Revision ID: bb9521665b62
Revises: 5462ce61485d
Create Date: 2026-08-21 23:45:53.826755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9521665b62'
down_revision: Union[str, Sequence[str], None] = '5462ce61485d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'REJECTED', 'INACTIVE', name='userstatus'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_owner_id'), ['owner_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shops_status'), ['status'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PRINTED', 'EXPIRED', name='documentstatus'),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_documents_expires_at'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.drop_column('encryption_status')
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_print_jobs_shop_id_shops', 'shops', ['shop_id'], ['id'])

    with op.batch_alter_table('shop_pricing', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_shop_pricing_shop_id_shops', 'shops', ['shop_id'], ['id'])

    # Migrate shop data from users to shops
    op.execute("""
        INSERT INTO shops (owner_id, shop_name, address, city, phone, status, created_at, updated_at)
        SELECT id, shop_name, address, city, phone, status, created_at, updated_at
        FROM users WHERE role = 'SHOP';
    """)

    # Update foreign keys for existing records
    op.execute("""
        UPDATE shop_pricing
        SET shop_id = (SELECT shops.id FROM shops WHERE shops.owner_id = shop_pricing.shop_id)
        WHERE EXISTS (SELECT 1 FROM shops WHERE shops.owner_id = shop_pricing.shop_id);
    """)
    op.execute("""
        UPDATE print_jobs
        SET shop_id = (SELECT shops.id FROM shops WHERE shops.owner_id = print_jobs.shop_id)
        WHERE EXISTS (SELECT 1 FROM shops WHERE shops.owner_id = print_jobs.shop_id);
    """)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('shop_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['shop_id'], ['id'])

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['shop_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('encryption_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PRINTED', 'EXPIRED', name='documentstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('page_count')

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_status'))
        batch_op.drop_index(batch_op.f('ix_shops_owner_id'))
        batch_op.drop_index(batch_op.f('ix_shops_id'))
        batch_op.drop_index(batch_op.f('ix_shops_city'))

    op.drop_table('shops')
    # ### end Alembic commands ###
