"""Add temporary access and audit log tables

Revision ID: d1c19e18295d
Revises: 1a1eeb693473
Create Date: 2026-08-31 10:25:15.174603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c19e18295d'
down_revision: Union[str, Sequence[str], None] = '1a1eeb693473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('print_job_id', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_print_job_id'), ['print_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('temporary_document_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='temporaryaccessstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporary_document_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporary_document_access_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_document_access_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_document_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_document_access_print_job_id'), ['print_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_document_access_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_document_access_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('temporary_document_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_status'))
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_shop_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_print_job_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_expires_at'))
        batch_op.drop_index(batch_op.f('ix_temporary_document_access_document_id'))

    op.drop_table('temporary_document_access')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_print_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_document_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
