"""Batch migration for shop fields and documents

Revision ID: fb6d456d4676
Revises: 
Create Date: 2026-08-21 22:21:00.311396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fb6d456d4676'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_qr_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_qr_tokens_status'))

    op.drop_table('qr_tokens')
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_customer_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_shop_id'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_status'))

    op.drop_table('print_jobs')
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printers_id'))

    op.drop_table('printers')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_id'))

    op.drop_table('pricing')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_city'))
        batch_op.drop_index(batch_op.f('ix_shops_id'))
        batch_op.drop_index(batch_op.f('ix_shops_status'))

    op.drop_table('shops')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'PRINTED', 'EXPIRED', name='documentstatus'),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_documents_expires_at'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('encryption_status')
        batch_op.drop_column('file_size')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('shop_name')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('encryption_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'PRINTED', 'EXPIRED', name='documentstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('pages')
        batch_op.drop_column('filename')
        batch_op.drop_column('user_id')

    op.create_table('shops',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('shop_name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_city'), ['city'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('device_info', sa.VARCHAR(), nullable=True),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('pricing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('paper_size', sa.VARCHAR(), nullable=False),
    sa.Column('color_mode', sa.VARCHAR(), nullable=False),
    sa.Column('price_per_page', sa.FLOAT(), nullable=False),
    sa.Column('single_side_price', sa.FLOAT(), nullable=True),
    sa.Column('double_side_price', sa.FLOAT(), nullable=True),
    sa.Column('binding_price', sa.FLOAT(), nullable=True),
    sa.Column('stapling_price', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_id'), ['id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('method', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.create_table('printers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('printer_name', sa.VARCHAR(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('paper_level', sa.INTEGER(), nullable=True),
    sa.Column('ink_level', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printers_id'), ['id'], unique=False)

    op.create_table('print_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('settings', sqlite.JSON(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accepted_at', sa.DATETIME(), nullable=True),
    sa.Column('printing_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('expired_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_created_at'), ['created_at'], unique=False)

    op.create_table('qr_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['print_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('qr_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_tokens_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    # ### end Alembic commands ###
